### ISSUE TITLE
Klassendiagramm (2 Rot)

### ISSUE THREAD

**Issue by alepu8** [russkimanski/yatzy#10]
Klassendiagramm erstellen mit allen Elementen und dazugehörigen Eigenschaften die in diesem Projekt verwendet werden.
Relationen zwischen den Elementen darstellen und entsprechend aufzeichnen.

- [Ablage OneDrive](https://tekoedu-my.sharepoint.com/:f:/g/personal/alessandro_pucci_edu_teko_ch/Eqos_E6F4Y5EhvGduUDvLc4B5mqrylzAf1dbxeUbEVt0Og?e=kUxVP5)
- [Draw.io](https://www.draw.io/#Wb!OK6n9uxTJEWoLDgtfJeMJxG6vf51Mo9CiEtUjYBt8gPWVLo1C75qSKSjX6mJl8oI%2F01JEG7QUMCU4M4T3EKBZC2OEE2QRULHSFX)

Bsp.: Würfel
- Zustand (welche Seite)
- Grösse (Länge)
- Wurf (kann geworfen werden)

Bsp.: Spieler
- Benutzername
- Reihenfolge (Spielablauf)
- Position (Punktestand)

**Comment by box-sudo** [comment]
Version hinzugefügt.

**Comment by box-sudo** [comment]
Neue Version 2 (Mit Viewer-Class und Inputs von Fabian)

https://tekoedu-my.sharepoint.com/:u:/g/personal/alessandro_pucci_edu_teko_ch/EVADWO9ku0pNpQVONByvlBIBficxVOKSX7aPtTZoN7p9RA?e=heydzR

**Comment by box-sudo** [comment]
Neue Version 3 (Korrekturen letztes Iterationsmeeting)

https://tekoedu-my.sharepoint.com/:u:/g/personal/alessandro_pucci_edu_teko_ch/EURwvJYX92BEtjEAF8B7kxMBYjxCLC4XnxqBO8imU_cCAg?e=SpK51y
